# Generated by Django 3.1.2 on 2020-12-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='close_eye_left',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='close_eye_right',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='open_eye_left',
            field=models.FloatField(default=0.6),
        ),
        migrations.AddField(
            model_name='user',
            name='open_eye_right',
            field=models.FloatField(default=0.6),
        ),
    ]
