# Generated by Django 3.1.2 on 2020-11-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_auto_20201106_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='days',
            name='day',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='start_time',
        ),
        migrations.AddField(
            model_name='days',
            name='days',
            field=models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='days',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='days',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='days',
            field=models.ManyToManyField(related_name='timetable', to='subject.Days'),
        ),
    ]
