# Generated by Django 3.1.2 on 2020-12-07 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('study', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystudyrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_record', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailystudyforsubject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_subject_record', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='concentration',
            name='parent_study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concentrations', to='study.dailystudyforsubject'),
        ),
    ]
