# Generated by Django 3.1.2 on 2020-11-18 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystudyrecord',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
