# Generated by Django 3.1.2 on 2020-11-22 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_auto_20201118_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concentration',
            name='image',
        ),
    ]
