# Generated by Django 3.1.2 on 2020-12-15 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_auto_20201215_1705'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TuneEyes',
        ),
    ]
