# Generated by Django 3.1.4 on 2020-12-15 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_auto_20201215_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailystudyforsubject',
            name='last_updated_time',
        ),
        migrations.AlterField(
            model_name='dailystudyforsubject',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='dailystudyforsubject',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
