# Generated by Django 3.1.2 on 2020-11-11 11:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0002_auto_20201110_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStudyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_study_time', models.DurationField(default=datetime.timedelta(0))),
                ('total_concentration', models.DurationField(default=datetime.timedelta(0))),
                ('total_gauge', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_record', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Daily_study_for_subject',
            new_name='DailyStudyForSubject',
        ),
        migrations.DeleteModel(
            name='Daily_study_record',
        ),
    ]
