# Generated by Django 3.1.4 on 2020-12-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_auto_20201215_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystudyforsubject',
            name='end_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dailystudyforsubject',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
