# Generated by Django 3.1.2 on 2020-10-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='password',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
