# Generated by Django 3.1.2 on 2020-11-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='password',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
