# Generated by Django 3.1.2 on 2020-10-30 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20201030_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyroom',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='group.group'),
        ),
    ]
