# Generated by Django 3.1.2 on 2020-11-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20201110_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='password',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
