# Generated by Django 3.1.2 on 2020-11-11 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20201111_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyroom',
            old_name='activeMembers',
            new_name='active_members',
        ),
    ]
