# Generated by Django 3.1.2 on 2020-12-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20201215_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
