# Generated by Django 3.1.2 on 2020-11-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_20201110_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='password',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
