# Generated by Django 3.1.2 on 2020-10-30 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_20201030_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
